### ISSUE TITLE
Addon installato ma non funzionante

### ISSUE THREAD

**Issue by Jorman** [autoscatto/tntvillage-cp-provider#1]
Ciao, premetto che ho installato il pacchetto su un nas qnap, ho cmq trovato la cartella per l'installazione e da CP vedo e posso configurare l'estensione.

Detto questo, provo a fare eseguire la ricerca a CP di un film che so essere presente di tnt, ma nel log non vedo traccia di connessione a tnt.

Può dipendere dal fatto che gira sul nas?
Come posso fare per fare una sorta di debug?

Grazie, J

**Comment by isadic** [comment]
Stesso problema, nel Log vedo il prefisso "THA UGLIEST" e quelle release vengono ignorate. Qualcuno è riuscito a risolvere?

**Comment by Skelos** [comment]
Cercando Ossessione D'amore
mi da il seguente errore: 
07-27 15:48:46ERROR[chpotato.core.plugins.log] API log: {'file': u'http://HOST/minified/head.js?1438003854', 'message': u'firefox 39: \nReferenceError: Updater is not defined', 'line': u'28', 'page': u'http://HOST/log/', '_request': <couchpotato.api.ApiHandler object at 0x73fe0310>}

**Comment by Bassysta** [comment]
confermo tutt'oggi il problema. nessuno è riuscito a darci un occhio?

**Comment by autoscatto** [comment]
Ho aggiornato il plugin con un ennesimo trucco.
Nel debug sarebbe utile sapere cosa dice nell'intorno di FAILED. 
In particolare  _[core.media.movie.searcher] Wrong: ****_

**Comment by Bassysta** [comment]
Ciao!
Ho fatto al volo un tentativo cercando il film "Rango".
Dati di TNT:
Nome:Rango (2011)
Descrizione:[BDrip 1080p - H264 - Eng Ita Ac3 5.1 - SoftSub Ita Eng]
dimensione =8GB

Purtroppo niente da fare, lo ignora e nei log alla voce [core.media.movie.searcher] Wrong: **** trovo solo i nomi di altri Film. ti allego i log della ricerca fatta da CP
[rango.txt](https://github.com/autoscatto/tntvillage-cp-provider/files/233549/rango.txt)

**Comment by autoscatto** [comment]
Non c'è Rango su tnt.
La ricerca sfrutta la ricerca di tnt. [http://forum.tntvillage.scambioetico.org/index.php?act=allreleases&filter=rango&releaser=&st=0&cat=4](qui)

**Comment by Bassysta** [comment]
ciao.
eccoti l screen della mia ricerca:
![2016-04-25 14_18_53-new notification](https://cloud.githubusercontent.com/assets/18572382/14783562/c6570a04-0af0-11e6-9a44-41fe1c0c623f.png)

l'ho scaricato 2 giorni fa da li, quindi quello che mi dici non è possibile :D

**Comment by autoscatto** [comment]
Fa la ricerca nella categoria Film, tra i Cartoon non cerca. 
E' un ottimo punto, aggiungo la ricerca multi categoria al prossimo aggiornamento.

**Comment by Bassysta** [comment]
Ciao.
Lieto di essere stato utile per quel "BUG".
ho fatto una prova con "lo chiamavano Trinità". ma nonlo trova.questo è tutto quello che ottengo dai log e di seguito le release di TNT
![2016-04-25 18_49_40-new notification](https://cloud.githubusercontent.com/assets/18572382/14791582/bfafb68a-0b16-11e6-8282-76d1b0c27683.png)
![2016-04-25 18_51_17-all releases](https://cloud.githubusercontent.com/assets/18572382/14791590/c38da80c-0b16-11e6-8553-94250ce99b51.png)

**Comment by Bassysta** [comment]
Non so se può esserti utilie, ma c'è un provider di TNT che gira su Sickrage per la ricerca delle serie tv, e funziona alla perfezione, magari può essere utile per qualche spunto

**Comment by Skelos** [comment]
Sai che non riesco a farlo funzionare (Sickrage su TntVillage)..... mi
sembra di aver fatto tutto e configurato per bene.Caspita non son un
novellino... e invece non mi trova niente! Mi rimane tutto su wanted...
Ho impostato come provider solo TntVillage...

E non riesco nemmeno ad accedere al forum perchè non mi arriva l'email
dell'attivazione dell' account...

Mi dici tu come l'hai impostato?

Scusa la rottura.

2016-04-25 21:25 GMT+02:00 Bassysta notifications@github.com:
