### ISSUE TITLE
La ricerca non produce risultati, anche se dovrebbe

### ISSUE THREAD

**Issue by isadic** [autoscatto/tntvillage-cp-provider#3]
Installando il plugin, ho notato che ricerca una query su forum.tntvillage.scambioetico.it/index.php, ma a volte capita che non trovi dei film che, in realtà, sul forum esistono.
Ad esempio, cercando su CouchPotato "Toy Story 2 - Woody e Buzz alla riscossa" non ottengo risultati, ma cercandolo sul forum si. Puoi dare un'occhiata?

**Comment by Njcki** [comment]
Same problem here:
[               tntvillage] Search entry processing FAILED!

**Comment by autoscatto** [comment]
Scusate la latitanza, il plugin è del tutto non mantenuto da molto tempo. Prometto di darci un occhio appena posso e aggiornarlo alla nuova architettura.

Per essere chiari comunque non restituirà mai in toto i risultati di TNT visto che non c'è un modo furbo per capire di che film si tratti, non hanno una policy dei nomi ne un tagging di nessun tipo (imdb/tmdb ids etc) e quindi la ricerca/identificazione è ad approssimazioni successive.

**Comment by autoscatto** [comment]
Ho dato un'occhiata e in linea di massima sembra funzionare. Ho switchato da magnet provider a .torrent provider in modo da poterlo utilizzare anche in configurazioni che prevedano un client non avvezzo ai magnet (ad es per le watch-dir). 

Per la ricerca l'unica cosa che posso suggerire è provare un po di ricerche similari, nel caso specifico "Toy Story 2 - Woody e Buzz alla riscossa" nel search del forum non ritorna nulla "Toy Story 2" si, e chiaramente il plugin si comporta nello stesso modo.

Ci sarebbe da richiedere a TNT di mettere a disposizione API furbe e una policy definita su template e nomi ma fanno orecchie da mercante. Se vogliamo cercare di normalizzare la situazione e sviluppare in quella direzione mi rendo disponibile.
