### ISSUE TITLE
Errore nel riconoscere la data se il locale non è en_US

### ISSUE THREAD

**Issue by Njcki** [autoscatto/tntvillage-cp-provider#4]
Ciao,
ho visto che la funzione ageToDays(self, age_str) restituisce errore in datetime.datetime.strptime(age_str, " %b %d %Y") in quanto il locale da me era impostato a italiano, mentre age_str contiene la data scritta in inglese (in pratica per il mese si aspetta Gen-Dic mentre troverà Jan-Dec).
Per risolvere e renderlo compatibile con ogni sistema basta impostare il locale a en_US:
        locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

Saluti

**Comment by autoscatto** [comment]
Alla prossima revisione vedo di fixare. 
Grazie della segnalazione.
